### ISSUE TITLE
TVL chart displays incorrect data for most recent day

### ISSUE THREAD

**Issue by 0xSzeth** [88mphapp/ng88mph-frontend#45]
![image](https://user-images.githubusercontent.com/80861276/134721172-c021bde4-5f4e-4e7f-bc4b-e5f91495f84b.png)

CoinGecko's API returns a 0 value for the price of some assets on the most recent day. The issue appears to happen within several hours of midnight UTC and resolves itself after a few hours. Probably due to CoinGecko not updating the price on their API.

**Comment by 0xSzeth** [comment]
Since we use Chainlink price feeds for the current prices of assets (when possible), it would make sense to use them for historical prices as well. A subgraph would make the most sense to achieve this in a scalable way vs calling the price feed contract directly for each period where an asset's price is needed. 

This subgraph appears to be a good option:
https://thegraph.com/legacy-explorer/subgraph/openpredict/chainlink-prices-subgraph

If a Chainlink price feed does not exist for an asset, we should continue to use CoinGecko's API until a better solution is found.

**Comment by guillaumepalayer** [comment]
thanks, deploying now
Guillaume Palayer
Mobile: (+33) 07 69 62 27 03
Fixe: (+33) 06 37 88 02 89
