### ISSUE TITLE
Develop "back to the future" subgraph for v2

### ISSUE THREAD

**Issue by 0xSzeth** [88mphapp/ng88mph-frontend#54]
The v2 subgraph restricts historical data indexing for fixed-interest rates as well as the surplus for each pool. Because of this, charts for Fixed-Rate Yield, Net Interest Margin, and Loss Provision cannot be reliably developed.

**Comment by guillaumepalayer** [comment]
Gotcha.
I deleted the v2 stats tab in the UI. Problem solved LOL
Guillaume Palayer
Mobile: (+33) 07 69 62 27 03
Fixe: (+33) 06 37 88 02 89
