### ISSUE TITLE
Metamask - RPC Error: header not found

### ISSUE THREAD

**Issue by 0xSzeth** [88mphapp/ng88mph-frontend#55]
The following Metamask error with an error code of -32000 is occasionally thrown, sometimes several times, which prevents data from loading in our app. It appears to occur sporadically (read: not all the time) and cannot be produced reliably. Since it prevents data from loading at all, this should be a high priority issue to resolve.

![image](https://user-images.githubusercontent.com/80861276/135501008-55504d9d-025b-49b5-af98-69977d2269d1.png)

**Comment by 0xSzeth** [comment]
This appears to be an Ethereum RPC error with a description of "Invalid Input" for the error code -32000

https://github.com/MetaMask/eth-rpc-errors/blob/main/src/error-constants.ts
https://www.npmjs.com/package/eth-rpc-errors

**Comment by 0xSzeth** [comment]
Here is a thread on the Metamask github repo discussing this error. Seems like it may be an issue with Infra, which makes sense given that it's an RPC error.

Looking at the stack trace, the error occurs whenever we `.call()` a contract method. Invalid input makes no sense, though, as many of these methods don't take an argument. At first blush, here's a couple of ideas to look into:

1. Many of the addresses we use are in lower case. Does converting them to checksum help the issue?
2. Do these contract methods take an argument where we aren't passing any arguments?
3. Should we be passing a { from: "0x..." } parameter when we make these calls?

https://github.com/MetaMask/metamask-extension/issues/7234

**Comment by 0xSzeth** [comment]
These errors started to occur more frequently after implementing the use of chainlink price feeds for asset prices, so I'm going to start by changing all of the chainlink price feed addresses to checksummed addresses to see if that helps at all.

**Comment by 0xSzeth** [comment]
Changing to checksum addresses appears to have helped. I've also changed all addresses in the `assets/json/pool.json` file to checksummed addresses and there's some decent evidence this was the issue -- I would get 2 -32000 errors and there were 2 pool addresses that were not checksummed. Will continue to monitor the issue to see if this solution resolves it.

**Comment by 0xSzeth** [comment]
Checksum addresses are not the solution, I'm still getting -32000 errors. Maybe this is an RPC rate limiting issue?

https://githubmemory.com/repo/ethersphere/bee/issues/1919

**Comment by jurgenwerk** [comment]
@0xSzeth thanks! For now it appears this approach solved our RPC issue mentioned above.

**Comment by 0xSzeth** [comment]
After some additional exploration here, I think I've found the solution.

This error occurs when using the Metamask injected provider to make contract calls. I.e. the provider we were using for contract calls was instantiated using...

`const provider = await detectEthereumProvider();`

However, this occasionally threw the aforementioned error. So, I tried instantiating a Web3 instance using both https and wss RPC providers to make contract calls from. Some details of each from the Web3 docs...

![image](https://user-images.githubusercontent.com/80861276/141000254-8dee9e13-26e6-4cde-b70b-9a452e2d5227.png)

If you do not need the contract call to be observable (e.g. querying a user's token balance for an ERC20), then the https provider is vastly superior in terms of speed and reliability compared to the wss and metamask injected web3 providers. More importantly, the aforementioned errors have completely disappeared when using the https provider. The code looks like this...

`const provider = new Web3(https://your_rpc_endpoint_here);`

I'll be implementing this approach throughout our app whenever we `.call()` a contract while continuing to use the injected provider for `.send()` to maintain observability.

@jurgenwerk you may be interested in this, so tagging for the notification.

**Comment by 0xSzeth** [comment]
I haven't encountered any of these errors since the latest changes were made, so I'm going to close this issue as resolved.
